spring:
  application:
    name: delivery-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/logistics?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    open-in-view: false

  data:
    redis:
      host: localhost
      port: 6379
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      topic:
        delivery:
          create: DeliveryCreateEvent

    consumer:
      group-id: group-delivery
      auto-offset-reset: earliest
      topic:
        order:
          create: OrderCreateEvent

server:
  port: 19050

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

command:
  exchange: logistics
  queue:
    infra: logistics.infra