spring:
  application:
    name: hub-route-service

  datasource:
    url: jdbc:mysql://db:3306/logistics
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: 6379
      username: default

  cache:
    type: redis
    redis:
      cache-null-values: false

service:
  api:
    key: ${API_KEY}

server:
  port: 19040

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90